Added .gitignore and .editorconfig files
wtfpython-web/wtfpython-web pull request #15
Opened 2018-06-24 15:48 UTC by pritamnegi

#13

2018-06-24 17:17 UTC, satwikkansal requested changes
Nice works, few comments. 

Ping once addressed, and we're good to go!

2018-06-24 17:17 UTC, satwikkansal commented on .gitignore
> +.mypy_cache/
Please add a newline at the end. It's a common standard to end files with a newline. https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2018-06-24 17:17 UTC, satwikkansal commented on .editorconfig
> +[*.{ini,py,py.tpl,rst}]
We don't have any `ini` or `.tpl` or `.rst`  files currently in the project.

2018-06-24 17:17 UTC, satwikkansal commented on .editorconfig
> +[*.{ini,py,py.tpl,rst}]
Please cross check what all files do we have currently in the repo, and adapt accordingly

2018-06-24 17:17 UTC, satwikkansal commented on .editorconfig
> +[*.{sh,bat.tpl,Makefile.tpl}]
Again, there are no such files present. We can add such entries later once we have these files in the codebase. I hope you get the idea :)

2018-06-24 17:19 UTC, satwikkansal commented
It seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages initially, including very experienced developers :) Standards vary from project to project.

The most important part is the first line of your commit message - we can use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.io/commit !

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

Cheers!

2018-06-25 11:13 UTC, pritamnegi commented
Please now review my PR. I have made the changes requested by mentors.

2018-06-25 15:26 UTC, satwikkansal requested changes
A couple of changes in .editorconfig. Otherwise we're good to go :+1:

2018-06-25 15:26 UTC, satwikkansal commented on .editorconfig
> +# EditorConfig is awesome: http://EditorConfig.org
We don't need this line :p

2018-06-25 15:26 UTC, satwikkansal commented on .editorconfig
> +
This is one extra line than blank line :)

2018-06-25 15:28 UTC, satwikkansal commented
Also, did you see https://github.com/wtfpython-web/wtfpython-web/pull/15#issuecomment-399772374 ?

2018-06-25 16:36 UTC, pritamnegi commented
In what way I should change my commit message??

2018-06-25 17:44 UTC, satwikkansal commented
Commit 1
```
.editorconfig: Add .editorconfig

Adds the .editorconfig file for the project.

Related to https://github.com/wtfpython-web/wtfpython-web/issues/13
```

Commit 2

```
.gitignore: Add .gitignore

Adds the .gitignore file for the project referenced from https://github.com/github/gitignore/blob/master/Python.gitignore

Closes https://github.com/wtfpython-web/wtfpython-web/issues/13
```

2018-06-25 19:36 UTC, realslimshanky commented
@pritamnegi I suggest you take a look at Github's [gitignore](https://github.com/github/gitignore) as well to check if we need something more for our project. Also, make sure your PR description is informative enough.

2018-06-26 04:12 UTC, pritamnegi commented
Ok as you say @realslimshanky

2018-06-26 07:18 UTC, closed without merging